import type {
  Evidence,
  GraphEntity,
  Investigation,
  Relationship,
} from "./types";

// Curated historical sources. Opportunity examples are explicitly illustrative.
// This dataset is never merged into a live investigation.
const evidence: Evidence[] = [
  {
    id: "flash",
    type: "paper",
    title:
      "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    source: "arXiv · NeurIPS 2022",
    url: "https://arxiv.org/abs/2205.14135",
    date: "2022-05-27",
    authors: [
      "Tri Dao",
      "Daniel Y. Fu",
      "Stefano Ermon",
      "Atri Rudra",
      "Christopher Ré",
    ],
    snippet:
      "An IO-aware exact attention algorithm that reduces reads and writes between GPU high-bandwidth memory and on-chip SRAM.",
    relevanceScore: 0.96,
    engine: "scholar",
    primary: true,
    metadata: {
      cluster: "Attention & memory",
      year: 2022,
      skills: ["CUDA", "PyTorch"],
    },
  },
  {
    id: "flash2",
    type: "paper",
    title:
      "FlashAttention-2: Faster Attention with Better Parallelism and Work Partitioning",
    source: "arXiv · ICLR 2024",
    url: "https://arxiv.org/abs/2307.08691",
    date: "2023-07-17",
    authors: ["Tri Dao"],
    snippet:
      "Improves parallelism and work partitioning to make exact attention faster and use GPU resources more effectively.",
    relevanceScore: 0.95,
    engine: "scholar",
    primary: true,
    metadata: { cluster: "Attention & memory", year: 2023 },
  },
  {
    id: "paged",
    type: "paper",
    title:
      "Efficient Memory Management for Large Language Model Serving with PagedAttention",
    source: "arXiv · SOSP 2023",
    url: "https://arxiv.org/abs/2309.06180",
    date: "2023-09-12",
    authors: [
      "Woosuk Kwon",
      "Zhuohan Li",
      "Siyuan Zhuang",
      "Ying Sheng",
      "Lianmin Zheng",
      "Cody Hao Yu",
      "Joseph E. Gonzalez",
      "Hao Zhang",
      "Ion Stoica",
    ],
    snippet:
      "PagedAttention manages attention key-value memory in non-contiguous blocks. The paper introduces vLLM, a serving system built around this approach.",
    relevanceScore: 0.98,
    engine: "scholar",
    primary: true,
    metadata: { cluster: "LLM serving", year: 2023, technology: "vLLM" },
  },
  {
    id: "awq",
    type: "paper",
    title:
      "AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration",
    source: "arXiv · MLSys 2024",
    url: "https://arxiv.org/abs/2306.00978",
    date: "2023-06-01",
    authors: [
      "Ji Lin",
      "Jiaming Tang",
      "Haotian Tang",
      "Shang Yang",
      "Wei-Ming Chen",
      "Wei-Chen Wang",
      "Guangxuan Xiao",
      "Xingyu Dang",
      "Chuang Gan",
      "Song Han",
    ],
    snippet:
      "An activation-aware approach to low-bit weight quantization, with a hardware-friendly implementation for efficient language-model inference.",
    relevanceScore: 0.94,
    engine: "scholar",
    primary: true,
    metadata: { cluster: "Quantization", year: 2023 },
  },
  {
    id: "tri",
    type: "person",
    title: "Tri Dao",
    source: "Researcher website",
    url: "https://tridao.me/",
    snippet:
      "Research on efficient deep learning, including the FlashAttention series.",
    relevanceScore: 0.94,
    engine: "web",
    primary: true,
  },
  {
    id: "song",
    type: "person",
    title: "Song Han",
    source: "MIT faculty website",
    url: "https://hanlab.mit.edu/songhan",
    snippet:
      "Research on efficient deep learning and hardware-aware machine learning.",
    relevanceScore: 0.92,
    engine: "web",
    primary: true,
  },
  {
    id: "berkeley",
    type: "institution",
    title: "UC Berkeley",
    source: "vLLM project",
    url: "https://vllm.ai/",
    snippet:
      "The PagedAttention publication and vLLM project connect efficient language-model serving to the Berkeley research ecosystem.",
    relevanceScore: 0.92,
    engine: "web",
    primary: true,
  },
  {
    id: "stanford",
    type: "institution",
    title: "Stanford University",
    source: "Stanford AI Lab",
    url: "https://ai.stanford.edu/",
    snippet:
      "A research institution represented in the affiliations of the original FlashAttention publication.",
    relevanceScore: 0.88,
    engine: "web",
    primary: true,
  },
  {
    id: "mit",
    type: "institution",
    title: "MIT",
    source: "MIT HAN Lab",
    url: "https://hanlab.mit.edu/",
    snippet:
      "Research in efficient AI, model compression, and hardware-aware systems.",
    relevanceScore: 0.91,
    engine: "web",
    primary: true,
  },
  {
    id: "nvidia",
    type: "company",
    title: "NVIDIA",
    source: "NVIDIA",
    url: "https://www.nvidia.com/en-us/ai/",
    snippet: "AI computing hardware and software infrastructure.",
    relevanceScore: 0.86,
    engine: "web",
    primary: true,
  },
  {
    id: "blackwell",
    type: "news",
    title: "NVIDIA Blackwell Platform Arrives to Power a New Era of Computing",
    source: "NVIDIA Newsroom",
    url: "https://nvidianews.nvidia.com/news/blackwell-ai-computing-platform",
    date: "2024-03-18",
    authors: ["NVIDIA"],
    snippet:
      "NVIDIA announced the Blackwell platform for accelerated computing, including generative AI workloads. This is a company announcement, not independent reporting.",
    relevanceScore: 0.83,
    engine: "news",
    primary: true,
    metadata: {
      event: "Blackwell announcement",
      stance: "context",
      year: 2024,
    },
  },
  {
    id: "vllm-news",
    type: "news",
    title: "vLLM: Easy, Fast, and Cheap LLM Serving with PagedAttention",
    source: "Berkeley AI Research",
    url: "https://bair.berkeley.edu/blog/2023/06/20/vllm/",
    date: "2023-06-20",
    snippet:
      "The project team introduces vLLM and explains the memory-management challenge behind PagedAttention.",
    relevanceScore: 0.95,
    engine: "news",
    primary: true,
    metadata: { event: "vLLM introduction", stance: "supports", year: 2023 },
  },
  {
    id: "hardware-patent",
    type: "patent",
    title: "Machine learning-based hardware component monitoring",
    source: "Google Patents · US11734097B1",
    url: "https://patents.google.com/patent/US11734097B1/en",
    date: "2023-08-22",
    authors: ["Christopher Golden"],
    snippet:
      "A real adjacent hardware-monitoring patent. It is included as an exploration example; no citation or invention lineage to FlashAttention or vLLM is asserted.",
    relevanceScore: 0.52,
    engine: "patents",
    primary: true,
    metadata: {
      patentId: "patent/US11734097B1/en",
      assignee: "Pure Storage Inc",
      priorityDate: "2018-01-18",
      publicationNumber: "US11734097B1",
      cluster: "Hardware intelligence",
      year: 2023,
    },
  },
  {
    id: "nvidia-job",
    type: "job",
    title: "AI Research Intern",
    source: "Illustrative opportunity · NVIDIA careers",
    url: "https://www.nvidia.com/en-us/about-nvidia/careers/",
    snippet:
      "An illustrative opportunity to demonstrate the radar. Visit the employer’s careers page to check actual vacancies and requirements.",
    relevanceScore: 0.9,
    engine: "jobs",
    metadata: {
      illustrative: true,
      company: "NVIDIA",
      location: "United States",
      schedule: "Internship",
      skills: ["Python", "PyTorch", "CUDA"],
      remote: false,
    },
  },
  {
    id: "mit-job",
    type: "job",
    title: "Efficient AI Research Internship",
    source: "Illustrative opportunity · MIT research",
    url: "https://urop.mit.edu/",
    snippet:
      "An illustrative student research opportunity. MIT UROP’s official website provides actual eligibility and opportunity information.",
    relevanceScore: 0.86,
    engine: "jobs",
    metadata: {
      illustrative: true,
      company: "MIT UROP",
      location: "Cambridge, United States",
      schedule: "Research internship",
      skills: ["Python", "PyTorch", "Research"],
      remote: false,
    },
  },
];

const positions: Record<string, [number, number, number]> = {
  topic: [0, 0, 0],
  flash: [-3.3, 1.3, 0.3],
  flash2: [2.4, 1.55, -0.3],
  paged: [-2, -1.2, 0.4],
  awq: [2.9, -1.1, 0],
  tri: [-5.6, 0.3, 0.1],
  song: [5.25, -0.3, 0.2],
  berkeley: [-4.4, -2.4, -0.2],
  stanford: [-5.4, 2.3, -0.6],
  mit: [5.3, 2.1, -0.2],
  nvidia: [4.5, -2.4, -0.2],
  blackwell: [6.65, -1.55, -0.8],
  "vllm-news": [-6.55, -1.45, -0.6],
  "hardware-patent": [0.5, -2.7, 0.3],
  "nvidia-job": [6.7, -3.2, -0.6],
  "mit-job": [7.1, 1.5, -0.5],
  technology: [-0.6, 2.4, -0.4],
  storage: [2, -3.8, -0.7],
};
const labels: Record<string, string> = {
  flash: "FlashAttention",
  flash2: "FlashAttention-2",
  paged: "PagedAttention",
  awq: "AWQ",
  blackwell: "Blackwell platform",
  "vllm-news": "The vLLM story",
  "hardware-patent": "Hardware intelligence",
  "nvidia-job": "AI research intern",
  "mit-job": "Research internship",
};
const entities: GraphEntity[] = [
  {
    id: "topic",
    type: "topic",
    title: "Efficient AI inference",
    label: "Efficient AI inference",
    subtitle: "A universe of connected ideas",
    position: positions.topic,
    evidenceIds: ["flash", "flash2", "paged", "awq"],
  },
  ...evidence.map((item) => ({
    id: item.id,
    type: item.type,
    title: item.title,
    label: labels[item.id] ?? item.title,
    subtitle: item.source,
    position: positions[item.id],
    evidenceIds: [item.id],
    metadata: item.metadata,
  })),
  {
    id: "technology",
    type: "technology",
    title: "GPU memory efficiency",
    label: "GPU memory",
    subtitle: "Technology cluster",
    position: positions.technology,
    evidenceIds: ["flash", "flash2", "paged"],
  },
  {
    id: "storage",
    type: "company",
    title: "Pure Storage",
    label: "Pure Storage",
    subtitle: "Patent assignee",
    position: positions.storage,
    evidenceIds: ["hardware-patent"],
  },
];
const edge = (
  source: string,
  target: string,
  type: Relationship["type"],
  ids: string[],
  inferred = false,
): Relationship => ({
  id: `${source}-${target}`,
  source,
  target,
  type,
  evidenceIds: ids,
  inferred,
});
const relationships = [
  ...["flash", "flash2", "paged", "awq"].map((id) =>
    edge("topic", id, "related_to", [id], true),
  ),
  edge("tri", "flash", "authored", ["flash"]),
  edge("tri", "flash2", "authored", ["flash2"]),
  edge("flash", "stanford", "related_to", ["flash"]),
  edge("paged", "berkeley", "related_to", ["paged"]),
  edge("song", "awq", "authored", ["awq"]),
  edge("song", "mit", "works_at", ["song"]),
  edge("paged", "vllm-news", "related_to", ["paged", "vllm-news"]),
  edge("blackwell", "nvidia", "reported_by", ["blackwell"]),
  edge("topic", "blackwell", "related_to", ["blackwell"], true),
  edge("topic", "technology", "related_to", ["flash", "paged"], true),
  edge("technology", "flash2", "related_to", ["flash2"], true),
  edge("awq", "mit", "related_to", ["awq"]),
  edge("hardware-patent", "storage", "assigned_to", ["hardware-patent"]),
  edge("topic", "hardware-patent", "related_to", ["hardware-patent"], true),
  edge("nvidia", "nvidia-job", "hiring_for", ["nvidia-job"], true),
  edge("mit", "mit-job", "hiring_for", ["mit-job"], true),
];

export const DEMO: Investigation = {
  id: "demo-efficient-inference",
  query: "What is happening in efficient AI inference?",
  demo: true,
  evidence,
  entities,
  relationships,
  summary:
    "Less memory. Better serving. More accessible AI. Explore how attention algorithms, memory management, and quantization connect the research to practical AI infrastructure.",
  whyItMatters:
    "These papers address different inference bottlenecks: attention IO, KV-cache management, and model weight storage. Understanding those differences helps you choose what to learn or investigate next.",
  claims: [
    {
      id: "memory",
      text: "Memory efficiency is a recurring theme in attention algorithms and language-model serving.",
      evidenceIds: ["flash", "flash2", "paged"],
      conflictingEvidenceIds: [],
      confidence: "high",
      rationale:
        "Directly described in three primary research papers from two distinct research lines. This is a narrow statement about these papers, not a claim about the entire field.",
    },
    {
      id: "quantization",
      text: "Activation-aware weight quantization is another route to reducing the resources needed for LLM inference.",
      evidenceIds: ["awq"],
      conflictingEvidenceIds: [],
      confidence: "medium",
      rationale:
        "Supported by the original AWQ paper. This sample does not include an independent evaluation of its results.",
    },
    {
      id: "serving",
      text: "PagedAttention’s memory-management approach underpins the vLLM serving system introduced by its authors.",
      evidenceIds: ["paged", "vllm-news"],
      conflictingEvidenceIds: [],
      confidence: "medium",
      rationale:
        "The paper and project introduction agree, but come from the same underlying research team and are counted as one source family.",
    },
    {
      id: "impact",
      text: "These papers address different inference bottlenecks: attention IO, KV-cache management, and model weight storage. Understanding those differences helps you choose what to learn or investigate next.",
      evidenceIds: ["flash", "flash2", "paged", "awq"],
      conflictingEvidenceIds: [],
      confidence: "medium",
      rationale:
        "The bottlenecks are described in the original research papers. Their relevance to your next learning decision is an interpretation, not a demonstrated public-impact outcome.",
    },
  ],
  sources: ["scholar", "jobs", "news", "patents", "web"].map((source) => ({
    source: source as Investigation["sources"][number]["source"],
    state: "success",
    count: evidence.filter((e) => e.engine === source).length,
  })),
  createdAt: "2026-10-05T00:00:00Z",
  warnings: [],
};

export const PROMPTS = [
  "What is happening in efficient AI inference?",
  "Which labs are hiring AI research interns?",
  "What changed in quantum computing this month?",
  "Who is working on climate AI?",
  "Find the latest research on multimodal medical AI",
];
